version: '3.8'

services:
  # Pixology Backend API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pixology-backend
    restart: unless-stopped
    ports:
      - "${PORT:-3001}:3001"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      # Mount logs directory for persistence
      - ./logs:/app/logs
      # Mount GCP credentials if using file-based auth
      - ./config:/app/config:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - pixology-network

networks:
  pixology-network:
    driver: bridge
